[package]
name = "rrm"
version = "0.1.0"
edition = "2021"

[dependencies]
redis = "0.23.0"
tui = "0.19.0"
crossterm = "0.25.0"
unicode-segmentation = "1.10.1"
thiserror = "1.0.40"
anyhow = "1.0.71"
clap = { version = "4.4.8", features = ["derive"] }
